# Generated by Django 5.2 on 2025-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
